name: Batch

on:
  schedule:
    - cron: 0 19 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - env:
          PIXE_LA_TOKEN: ${{ secrets.PIXE_LA_TOKEN }}
        run: |
          npm install
          npm run start
          npm run views
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "batch"
          git config --global user.email "m@jgs.me"
          git remote set-url origin https://kbystk:${GITHUB_TOKEN}@github.com/kbystk/amp.git
          git checkout master
          git status
          git add .
          git commit -m 'Update'
          git push origin HEAD
      - env:
          Y_HOOK_URL: ${{ secrets.Y_HOOK_URL }}
        run: curl -X POST -d {} $Y_HOOK_URL
