name: Batch

on:
  schedule: 
  - cron: 06 * * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: node --version
    - run: yarn --version
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "batch"
        git config --global user.email "m@jgs.me"
        git config --get user.name
